# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-10 12:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shop.models
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u0430')),
                ('created_at', models.DateTimeField(default=shop.models.get_default_now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0438\u043b\u0438 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('title', models.CharField(help_text='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0438 \u0442\u0435\u0433 title', max_length=100)),
                ('page_description', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 description')),
                ('page_keywords', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords')),
                ('image', models.ImageField(blank=True, upload_to='articles')),
                ('html', models.TextField(help_text="\u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0439\u0442\u0435 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0434\u043b\u044f \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430 \u0447\u0435\u0440\u0435\u0437 <a href=''>\u044d\u0442\u0443 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443</a>; \u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 URL \u0432\u0438\u0434\u0430 /media/resize/<\u0448\u0438\u0440\u0438\u043d\u0430>/<\u043e\u0441\u0442\u0430\u043b\u044c\u043d\u043e\u0435>.jpg \u0434\u043b\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0430\u0437\u043c\u0435\u0440\u0430 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438.")),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='AutoPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043a\u0438\u0434\u043a\u0438')),
                ('code', models.CharField(max_length=50, verbose_name='\u041a\u043e\u0434')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variable_discount', models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 %')),
                ('fixed_discount', models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u0440\u0443\u0431\u043b\u044f\u0445')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u0441')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u0437\u0430\u043a\u0430\u043d\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='0 \u0437\u043d\u0430\u0447\u0438\u0442 \u0431\u0435\u0441\u043a\u043e\u043d\u0435\u0447\u043d\u043e', verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439')),
                ('used_times', models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e')),
                ('session_key', models.CharField(max_length=200, verbose_name='\u041a\u043b\u044e\u0447 \u0441\u0435\u0441\u0441\u0438\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
            ],
            options={
                'verbose_name': '\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u043f\u0440\u043e\u043c\u043e-\u043a\u043e\u0434',
                'verbose_name_plural': '\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u043f\u0440\u043e\u043c\u043e-\u043a\u043e\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='\n    \u042d\u0442\u043e\u0442 URL \u043c\u043e\u0436\u043d\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0432 \u043b\u044e\u0431\u043e\u043c \u043c\u0435\u0441\u0442\u0435 \u0441\u0430\u0439\u0442\u0430.\n    <br>\u041d\u0435 \u0443\u0434\u0430\u043b\u044f\u0439 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0431\u0435\u0437 \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u0438 (\u043d\u0435 \u043f\u0440\u043e\u0432\u0435\u0440\u0438\u0432 \u043a\u043e\u043d\u0442\u0435\u043d\u0442).\n    <br><br>\u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0439 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0443 \u043c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0440\u0430\u0437\u043c\u0435\u0440\u0430!\n    <br><br>\u0417\u0430\u0442\u0435\u043c, \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 URL \u0434\u043b\u044f \u0440\u0435\u0441\u0430\u0439\u0437\u0430 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438:\n    <br>&nbsp;/media/resize/<\u0448\u0438\u0440\u0438\u043d\u0430>/<\u043e\u0441\u0442\u0430\u043b\u044c\u043d\u043e\u0435>.jpg\n    <br>&nbsp;/media/resize/<\u0448\u0438\u0440\u0438\u043d\u0430>x<\u0432\u044b\u0441\u043e\u0442\u0430>/<\u043e\u0441\u0442\u0430\u043b\u044c\u043d\u043e\u0435>.jpg\n    <br>&nbsp;/media/crop/<\u0448\u0438\u0440\u0438\u043d\u0430>/<\u043e\u0441\u0442\u0430\u043b\u044c\u043d\u043e\u0435>.jpg</li>\n    <br>&nbsp;/media/crop/<\u0448\u0438\u0440\u0438\u043d\u0430>x<\u0432\u044b\u0441\u043e\u0442\u0430>/<\u043e\u0441\u0442\u0430\u043b\u044c\u043d\u043e\u0435>.jpg\n    ', upload_to='content-img')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0432 \u043a\u043e\u043d\u0442\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0432 \u043a\u043e\u043d\u0442\u0435\u043d\u0442',
            },
        ),
        migrations.CreateModel(
            name='OperationalDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('day_type', models.CharField(choices=[('normal', 'normal'), ('day-off', 'day-off')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_to_managers', models.BooleanField(default=False)),
                ('sent_to_telegram_bot', models.BooleanField(default=False)),
                ('sent_to_retailcrm', models.BooleanField(default=False)),
                ('retailcrm_order_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_product_kit', models.BooleanField(default=False, help_text="\u041d\u0415 \u041f\u0415\u0420\u0415\u041a\u041b\u042e\u0427\u0410\u0422\u042c \u0411\u0415\u0417 \u041d\u0415\u041e\u0411\u0425\u041e\u0414\u0418\u041c\u041e\u0421\u0422\u0418! \u041f\u0435\u0440\u0435\u043d\u043e\u0441\u0438\u0442 \u0442\u043e\u0432\u0430\u0440 \u0432 \u0442\u0430\u0431\u043b\u0438\u0446\u0443 '\u043d\u0430\u0431\u043e\u0440\u044b', \u044d\u0442\u043e \u0443\u0434\u0430\u043b\u0438\u0442 \u0437\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0443\u044e \u0446\u0435\u043d\u0443, \u0438 \u043e\u0441\u0442\u0430\u0442\u043a\u0438 \u0432 RetailCRM!", verbose_name='\u042f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u043d\u0430\u0431\u043e\u0440\u043e\u043c')),
                ('best_before_1', models.DateField(blank=True, help_text='\u0441\u0442\u0430\u0440\u0430\u044f \u043f\u0430\u0440\u0442\u0438\u044f', null=True, verbose_name='\u0413\u043e\u0434\u0435\u043d \u0434\u043e')),
                ('best_before_2', models.DateField(blank=True, help_text='\u043d\u043e\u0432\u0430\u044f \u043f\u0430\u0440\u0442\u0438\u044f', null=True, verbose_name='\u0413\u043e\u0434\u0435\u043d \u0434\u043e (\u043d\u043e\u0432\u0430\u044f)')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('retailcrm_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID \u0438\u0437 RetailCRM')),
                ('short_name', models.CharField(help_text='\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0435 \u0438\u043c\u044f, \u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b', max_length=300, verbose_name='\u0418\u043c\u044f')),
                ('ru_name', models.CharField(blank=True, help_text='\u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b', max_length=300, verbose_name='\u0418\u043c\u044f (\u0440\u0443\u0441)')),
                ('short_info', models.CharField(max_length=40)),
                ('slug', models.CharField(blank=True, max_length=40)),
                ('preview', models.ImageField(upload_to='product-previews')),
                ('price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('count_available', models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0435 \u0434\u043b\u044f \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('preorder', models.DateField(blank=True, null=True, verbose_name='\u041f\u0440\u0435\u0434\u0437\u0430\u043a\u0430\u0437')),
                ('is_market_test', models.BooleanField(default=False, help_text='\u0422\u0435\u0441\u0442 \u0440\u044b\u043d\u043a\u0430, \u043b\u0438\u0431\u043e \u0442\u043e\u0432\u0430\u0440 \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043c\u044b \u0437\u0430\u043a\u0443\u043f\u0430\u0435\u043c \u043e\u043f\u0435\u0440\u0430\u0442\u0438\u0432\u043d\u043e. \u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435 \u0434\u043b\u044f \u0442\u0430\u043a\u043e\u0433\u043e \u0442\u043e\u0432\u0430\u0440\u0430 \u043d\u0435 \u0443\u0447\u0438\u0442\u044b\u0432\u0430\u0435\u0442\u0441\u044f!', verbose_name='\u0422\u0435\u0441\u0442 \u0440\u044b\u043d\u043a\u0430')),
                ('is_new', models.BooleanField(default=True, verbose_name='\u041d\u043e\u0432\u0438\u043d\u043a\u0430')),
                ('overlay_image', models.ImageField(blank=True, upload_to='product-overlays', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043f\u043e\u0432\u0435\u0440\u0445')),
                ('page_title', models.CharField(blank=True, max_length=1000, verbose_name='\u0422\u0435\u0433 title \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435')),
                ('page_description', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 description \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435')),
                ('page_keywords', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435')),
                ('description_html', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images')),
                ('descripton', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0422\u043e\u0432\u0430\u0440\u0430',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0422\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='ProductKitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='shop.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_kits', to='shop.Product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailcrm_offers', to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='\u0420\u0430\u0437\u0440\u0435\u0448\u0430\u0435\u0442\u0441\u044f \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0442\u043e\u0442 \u0436\u0435 \u043a\u043e\u0434, \u0435\u0441\u043b\u0438 \u0441\u0442\u0430\u0440\u0430\u044f \u0430\u043a\u0446\u0438\u044f \u0443\u0436\u0435 \u043d\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u0430.', max_length=50)),
                ('name', models.CharField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u043f\u043e\u043a\u0430\u0437\u0430\u043d\u043e \u043a\u043b\u0438\u0435\u043d\u0442\u0443. \u041c\u043e\u0436\u043d\u043e \u043e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043f\u0443\u0441\u0442\u044b\u043c.', max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043a\u0438\u0434\u043a\u0438/\u0430\u043a\u0446\u0438\u0438')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variable_discount', models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 %')),
                ('fixed_discount', models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u0440\u0443\u0431\u043b\u044f\u0445')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u0441')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u0437\u0430\u043a\u0430\u043d\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='0 \u0437\u043d\u0430\u0447\u0438\u0442 \u0431\u0435\u0441\u043a\u043e\u043d\u0435\u0447\u043d\u043e', verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439')),
                ('used_times', models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u043c\u043e-\u041a\u043e\u0434',
                'verbose_name_plural': '\u041f\u0440\u043e\u043c\u043e-\u041a\u043e\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.CharField(max_length=15, unique=True)),
                ('header_id', models.CharField(max_length=20)),
                ('page_title', models.CharField(blank=True, max_length=1000, verbose_name='\u0422\u0435\u0433 title')),
                ('page_description', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 description')),
                ('page_keywords', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords')),
                ('products', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='shop.Product')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0437\u0434\u0435\u043b',
                'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_redirect', models.CharField(default='/section/hits/', max_length=500)),
                ('callback_button', models.CharField(blank=True, choices=[('', '\u0411\u0435\u0437 \u043a\u043d\u043e\u043f\u043a\u0438'), ('zadarma-01', 'zadarma-01'), ('zadarma-02', 'zadarma-02'), ('zadarma-03', 'zadarma-03')], max_length=100, verbose_name='\u041a\u043d\u043e\u043f\u043a\u0430 \u043e\u0431\u0440\u0430\u0442\u043d\u043e\u0433\u043e \u0437\u0432\u043e\u043d\u043a\u0430')),
                ('product_description_template', models.TextField(blank=True, help_text='\u041a\u043e\u043f\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043f\u0440\u0438 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u0438 \u043d\u043e\u0432\u043e\u0433\u043e \u0442\u043e\u0432\u0430\u0440\u0430 \u0447\u0435\u0440\u0435\u0437 CRM', verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u0430\u0439\u0442\u0430',
                'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u0441\u0430\u0439\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('updates_offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBotRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=500, unique=True)),
                ('authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.TelegramBot')),
            ],
        ),
        migrations.CreateModel(
            name='ProductKitModelProxy',
            fields=[
            ],
            options={
                'verbose_name': '\u041d\u0430\u0431\u043e\u0440',
                'proxy': True,
                'verbose_name_plural': '\u041d\u0430\u0431\u043e\u0440\u044b',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='ProductOrKitSelectorModelProxy',
            fields=[
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440 \u0438\u043b\u0438 \u041d\u0430\u0431\u043e\u0440',
                'proxy': True,
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440 \u2190\u2192 \u041d\u0430\u0431\u043e\u0440',
            },
            bases=('shop.product',),
        ),
    ]
