# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181105_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['retailcrm_slug'], 'verbose_name': '\u0421\u043a\u043b\u0430\u0434', 'verbose_name_plural': '\u0421\u043a\u043b\u0430\u0434\u044b'},
        ),
        migrations.AddField(
            model_name='store',
            name='has_kit_packer',
            field=models.BooleanField(default=False, verbose_name='\u0415\u0441\u0442\u044c \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a, \u0443\u043f\u0430\u043a\u043e\u0432\u044b\u0432\u0430\u044e\u0449\u0438\u0439 \u043d\u0430\u0431\u043e\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='productoffercount',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts_in_stores', to='shop.ProductOffer'),
        ),
    ]
