# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='products',
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
