# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-07 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181105_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffercount',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='productoffercount',
            name='store',
        ),
        migrations.DeleteModel(
            name='ProductOfferCount',
        ),
    ]
