# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 16:45
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20161115_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='products',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='shop.Product'),
        ),
    ]
