# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_section_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
