# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181107_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOfferCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts_in_stores', to='shop.ProductOffer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Store')),
            ],
        ),
    ]
