# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productoffercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
