# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='work_hours',
            field=models.CharField(default='', max_length=500, verbose_name='\u0427\u0430\u0441\u044b \u0440\u0430\u0431\u043e\u0442\u044b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=500, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
