# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181111_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cart_name',
            field=models.CharField(default='', max_length=200, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u043a\u043e\u0440\u0437\u0438\u043d\u044b'),
            preserve_default=False,
        ),
    ]
