# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='priority_for_courier',
            field=models.FloatField(default=50, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0434\u043b\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438 \u043a\u0443\u0440\u044c\u0435\u0440\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='store',
            name='priority_for_post',
            field=models.FloatField(default=50, verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u0434\u043b\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u043f\u043e\u0447\u0442\u043e\u0439'),
        ),
    ]
