# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20161116_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
