# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_store_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.CharField(blank=True, help_text='\u0425\u044d\u0448\u0442\u044d\u0433\u0438, \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e.', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='search_field',
            field=models.CharField(blank=True, help_text='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430.', max_length=1000),
        ),
    ]
