# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20161125_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, upload_to='product-previews'),
        ),
    ]
