# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-03 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190203_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='search_field',
            new_name='search_text',
        ),
    ]
