# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190203_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exclude_from_search',
            field=models.BooleanField(default=False, help_text='\u0418\u0441\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0438\u0437 \u043f\u043e\u0438\u0441\u043a\u0430.'),
        ),
    ]
