# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20161125_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_info',
            field=models.CharField(max_length=40),
        ),
    ]
