# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_exclude_from_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preview',
            new_name='image_original',
        ),
        migrations.AddField(
            model_name='product',
            name='image_compressed',
            field=models.ImageField(blank=True, help_text='\u0421\u0436\u0438\u043c\u0430\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043d\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0435', upload_to='product-previews-compressed'),
        ),
    ]
