# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 12:19
from __future__ import unicode_literals

from django.db import migrations
from transliterate import translit
from django.utils.text import slugify

def update_slugs(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    for p in Product.objects.all():
        p.slug = slugify(translit(p.short_name, 'ru', reversed=True), allow_unicode=False)
        p.save()
        print p.short_name, p.slug

def undo(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20161126_1407'),
    ]

    operations = [
        migrations.RunPython(update_slugs, reverse_code=undo)
    ]
