# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_image_compressed_with_tinypng'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_to_customer',
            field=models.BooleanField(default=False),
        ),
    ]
