# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verified_data',
            field=models.TextField(),
        ),
    ]
