# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20161203_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder',
            field=models.DateField(blank=True, null=True, verbose_name='\u041f\u0440\u0435\u0434\u0437\u0430\u043a\u0430\u0437'),
        ),
    ]
