# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_overlay_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 description'),
        ),
        migrations.AddField(
            model_name='section',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords'),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u0433 <title>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='overlay_image',
            field=models.ImageField(blank=True, upload_to='product-overlays', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043f\u043e\u0432\u0435\u0440\u0445'),
        ),
    ]
