# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20170210_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\u0422\u0435\u0433 <title>'),
        ),
    ]
