# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20170210_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 description'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\u0422\u0435\u0433 <title>'),
        ),
    ]
