# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20170210_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='description',
            new_name='page_description',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='keywords',
            new_name='page_keywords',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='title',
            new_name='page_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='page_description',
            field=models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 description \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AddField(
            model_name='product',
            name='page_keywords',
            field=models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AddField(
            model_name='product',
            name='page_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\u0422\u0435\u0433 <title> \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
    ]
