# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20170210_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='callback_button',
            field=models.CharField(choices=[('', '\u0411\u0435\u0437 \u043a\u043d\u043e\u043f\u043a\u0438'), ('zadarma-01', 'zadarma-01'), ('zadarma-02', 'zadarma-02'), ('zadarma-03', 'zadarma-03')], default='zadarma-01', max_length=100, verbose_name='\u041a\u043d\u043e\u043f\u043a\u0430 \u043e\u0431\u0440\u0430\u0442\u043d\u043e\u0433\u043e \u0437\u0432\u043e\u043d\u043a\u0430'),
            preserve_default=False,
        ),
    ]
