# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_sitepreferences_callback_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0438\u043b\u0438 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('title', models.CharField(blank=True, help_text='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0438 \u0442\u0435\u0433 <title>', max_length=1000)),
                ('page_description', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 description')),
                ('page_keywords', models.TextField(blank=True, verbose_name='\u041c\u0435\u0442\u0430-\u0442\u0435\u0433 keywords')),
                ('image', models.ImageField(upload_to='articles')),
                ('html', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='callback_button',
            field=models.CharField(blank=True, choices=[('', '\u0411\u0435\u0437 \u043a\u043d\u043e\u043f\u043a\u0438'), ('zadarma-01', 'zadarma-01'), ('zadarma-02', 'zadarma-02'), ('zadarma-03', 'zadarma-03')], max_length=100, verbose_name='\u041a\u043d\u043e\u043f\u043a\u0430 \u043e\u0431\u0440\u0430\u0442\u043d\u043e\u0433\u043e \u0437\u0432\u043e\u043d\u043a\u0430'),
        ),
    ]
