# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20170303_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_product_id',
            field=models.CharField(help_text='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0434\u043b\u044f \u0441\u0432\u044f\u0437\u0438 \u0441 RetailCRM - \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u0446\u0435\u043d, \u043d\u0430\u043b\u0438\u0447\u0438\u044f, \u0438 \u0442.\u043f.', max_length=100, null=True, unique=True, verbose_name='\u041d\u043e\u0432\u044b\u0439 \u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
    ]
