# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 22:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20170303_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email_to_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sync_to_frontpad',
        ),
        migrations.RemoveField(
            model_name='order',
            name='verified_data',
        ),
        migrations.AddField(
            model_name='order',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_retailcrm',
            field=models.BooleanField(default=False),
        ),
    ]
