# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20170307_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043a\u0438\u0434\u043a\u0438')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variable_discount', models.PositiveIntegerField(verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u043f\u0440\u043e\u0446\u0435\u043d\u0442\u0430\u0445')),
                ('constant_discount', models.PositiveIntegerField(verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u0440\u0443\u0431\u043b\u044f\u0445')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u0441')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u0437\u0430\u043a\u0430\u043d\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432')),
                ('code', models.CharField(max_length=50)),
                ('usage_count', models.IntegerField(default=0, verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439')),
                ('used_times', models.IntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e')),
                ('session_key', models.CharField(max_length=200, verbose_name='\u041a\u043b\u044e\u0447 \u0441\u0435\u0441\u0441\u0438\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043a\u0438\u0434\u043a\u0438')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variable_discount', models.PositiveIntegerField(verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u043f\u0440\u043e\u0446\u0435\u043d\u0442\u0430\u0445')),
                ('constant_discount', models.PositiveIntegerField(verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u0440\u0443\u0431\u043b\u044f\u0445')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u0441')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u0437\u0430\u043a\u0430\u043d\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432')),
                ('code', models.CharField(max_length=50)),
                ('usage_count', models.IntegerField(default=0, verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439')),
                ('used_times', models.IntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e')),
            ],
        ),
    ]
