# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_autopromocode_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopromocode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='constant_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u0440\u0443\u0431\u043b\u044f\u0445'),
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u0437\u0430\u043a\u0430\u043d\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432'),
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u0441'),
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='0 \u0437\u043d\u0430\u0447\u0438\u0442 \u0431\u0435\u0441\u043a\u043e\u043d\u0435\u0447\u043d\u043e', verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='variable_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 %'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='constant_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u0440\u0443\u0431\u043b\u044f\u0445'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u0437\u0430\u043a\u0430\u043d\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u0432'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u0435 \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u0441'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='variable_discount',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 %'),
        ),
    ]
