# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20170308_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopromocode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='0 \u0437\u043d\u0430\u0447\u0438\u0442 \u0431\u0435\u0441\u043a\u043e\u043d\u0435\u0447\u043d\u043e', verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='used_times',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_times',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e'),
        ),
    ]
