# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20170308_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autopromocode',
            options={'verbose_name': '\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u043f\u0440\u043e\u043c\u043e-\u043a\u043e\u0434', 'verbose_name_plural': '\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u043f\u0440\u043e\u043c\u043e-\u043a\u043e\u0434\u044b'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': '\u041f\u0440\u043e\u043c\u043e-\u041a\u043e\u0434', 'verbose_name_plural': '\u041f\u0440\u043e\u043c\u043e-\u041a\u043e\u0434\u044b'},
        ),
        migrations.AlterModelManagers(
            name='autopromocode',
            managers=[
                ('objects_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='promocode',
            managers=[
                ('objects_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='autopromocode',
            old_name='constant_discount',
            new_name='fixed_discount',
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='constant_discount',
            new_name='fixed_discount',
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='session_key',
            field=models.CharField(max_length=200, verbose_name='\u041a\u043b\u044e\u0447 \u0441\u0435\u0441\u0441\u0438\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(help_text='\u0420\u0430\u0437\u0440\u0435\u0448\u0430\u0435\u0442\u0441\u044f \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0442\u043e\u0442 \u0436\u0435 \u043a\u043e\u0434, \u0435\u0441\u043b\u0438 \u0441\u0442\u0430\u0440\u0430\u044f \u0430\u043a\u0446\u0438\u044f \u0443\u0436\u0435 \u043d\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u0430.', max_length=50),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
    ]
