# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_product_new_product_id'),
        ('shop', '0035_auto_20170309_0210'),
    ]

    operations = [
    ]
