# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='autopromocode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='promocode',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='count_available',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0435 \u0434\u043b\u044f \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='autopromocode',
            name='used_times',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_product_id',
            field=models.CharField(blank=True, help_text='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0434\u043b\u044f \u0441\u0432\u044f\u0437\u0438 \u0441 RetailCRM - \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u0446\u0435\u043d, \u043d\u0430\u043b\u0438\u0447\u0438\u044f, \u0438 \u0442.\u043f.', max_length=100, null=True, unique=True, verbose_name='\u041d\u043e\u0432\u044b\u0439 \u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u043f\u043e\u043a\u0430\u0437\u0430\u043d\u043e \u043a\u043b\u0438\u0435\u043d\u0442\u0443. \u041c\u043e\u0436\u043d\u043e \u043e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043f\u0443\u0441\u0442\u044b\u043c.', max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043a\u0438\u0434\u043a\u0438/\u0430\u043a\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='0 \u0437\u043d\u0430\u0447\u0438\u0442 \u0431\u0435\u0441\u043a\u043e\u043d\u0435\u0447\u043d\u043e', verbose_name='\u041c\u0430\u043a\u0441 \u043a\u043e\u043b-\u0432\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_times',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u043e\u043b\u044c\u043a\u043e \u0440\u0430\u0437 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u043e'),
        ),
    ]
