# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20170320_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retailcrm_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID \u0438\u0437 RetailCRM'),
        ),
    ]
