# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_product_retailcrm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_kit',
            field=models.BooleanField(default=False, verbose_name='\u042f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u043d\u0430\u0431\u043e\u0440\u043e\u043c \u0442\u043e\u0432\u0430\u0440\u043e\u0432'),
        ),
    ]
