# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_product_is_product_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
