# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20170324_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkititem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='in_kits', to='shop.Product'),
            preserve_default=False,
        ),
    ]
