# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_productkititem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField()),
                ('count', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0422\u043e\u0432\u0430\u0440\u0430', 'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0422\u043e\u0432\u0430\u0440\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='productkititem',
            options={'ordering': ['order']},
        ),
    ]
