# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_productoffers_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOffers',
            new_name='ProductOffer',
        ),
    ]
