# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20170328_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_before_2',
            field=models.DateField(blank=True, help_text='\u043d\u043e\u0432\u0430\u044f \u043f\u0430\u0440\u0442\u0438\u044f', null=True, verbose_name='\u0413\u043e\u0434\u0435\u043d \u0434\u043e (\u043d\u043e\u0432\u0430\u044f)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
