# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20170407_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
