# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_remove_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retailcrm_order_id',
            field=models.IntegerField(null=True),
        ),
    ]
