# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_order_retailcrm_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent_to_telegram_bot',
            field=models.BooleanField(default=True),
        ),
    ]
