# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_telegrambotrecipients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramBotRecipients',
            new_name='TelegramBotRecipient',
        ),
    ]
