# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20170529_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotrecipient',
            name='updates_offset',
            field=models.IntegerField(default=0),
        ),
    ]
