# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_telegrambotrecipient_updates_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('updates_offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='telegrambotrecipient',
            name='updates_offset',
        ),
        migrations.AddField(
            model_name='telegrambotrecipient',
            name='bot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.TelegramBot'),
            preserve_default=False,
        ),
    ]
