# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20170529_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
