# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_telegrambot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_market_test',
            field=models.BooleanField(default=False, help_text='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435 \u0434\u043b\u044f \u0442\u0430\u043a\u043e\u0433\u043e \u0442\u043e\u0432\u0430\u0440\u0430 \u043d\u0435 \u0443\u0447\u0438\u0442\u044b\u0432\u0430\u0435\u0442\u0441\u044f!', verbose_name='\u0422\u0435\u0441\u0442 \u0440\u044b\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_product_kit',
            field=models.BooleanField(default=False, help_text="\u041d\u0415 \u041f\u0415\u0420\u0415\u041a\u041b\u042e\u0427\u0410\u0422\u042c \u0411\u0415\u0417 \u041d\u0415\u041e\u0411\u0425\u041e\u0414\u0418\u041c\u041e\u0421\u0422\u0418! \u041f\u0435\u0440\u0435\u043d\u043e\u0441\u0438\u0442 \u0442\u043e\u0432\u0430\u0440 \u0432 \u0442\u0430\u0431\u043b\u0438\u0446\u0443 '\u043d\u0430\u0431\u043e\u0440\u044b', \u044d\u0442\u043e \u0443\u0434\u0430\u043b\u0438\u0442 \u0437\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0443\u044e \u0446\u0435\u043d\u0443, \u0438 \u043e\u0441\u0442\u0430\u0442\u043a\u0438!", verbose_name='\u042f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u043d\u0430\u0431\u043e\u0440\u043e\u043c \u0442\u043e\u0432\u0430\u0440\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_product_id',
            field=models.CharField(blank=True, help_text='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0434\u043b\u044f \u0441\u0432\u044f\u0437\u0438 \u0441 RetailCRM - \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u0446\u0435\u043d, \u043d\u0430\u043b\u0438\u0447\u0438\u044f, \u0438 \u0442.\u043f.', max_length=100, null=True, unique=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
    ]
