# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20170601_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='\u042d\u0442\u043e\u0442 URL \u043c\u043e\u0436\u043d\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0432 \u043b\u044e\u0431\u043e\u043c \u043c\u0435\u0441\u0442\u0435 \u0441\u0430\u0439\u0442\u0430. \u041d\u0435 \u0443\u0434\u0430\u043b\u044f\u0439 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0431\u0435\u0437 \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u0438 (\u043d\u0435 \u043f\u0440\u043e\u0432\u0435\u0440\u0438\u0432 \u043a\u043e\u043d\u0442\u0435\u043d\u0442).', upload_to='content-img')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0432 \u043a\u043e\u043d\u0442\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0432 \u043a\u043e\u043d\u0442\u0435\u043d\u0442',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='html',
            field=models.TextField(help_text="\u0417\u0430\u0433\u0440\u0443\u0436\u0430\u0439\u0442\u0435 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0434\u043b\u044f \u043a\u043e\u043d\u0442\u0435\u043d\u0442\u0430 \u0447\u0435\u0440\u0435\u0437 <a href=''>\u044d\u0442\u0443 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443</a>; \u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 URL \u0432\u0438\u0434\u0430 /media/resize/<\u0448\u0438\u0440\u0438\u043d\u0430>/<\u043e\u0441\u0442\u0430\u043b\u044c\u043d\u043e\u0435>.jpg \u0434\u043b\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0430\u0437\u043c\u0435\u0440\u0430 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438."),
        ),
    ]
