# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_auto_20170706_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_product_id',
            new_name='article',
        ),
    ]
