# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_auto_20170707_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, help_text='\u0434\u043b\u044f \u0434\u043b\u0438\u043d\u043d\u043e\u0433\u043e \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f', max_length=1000, verbose_name='\u0414\u043b\u0438\u043d\u043d\u043e\u0435 \u0438\u043c\u044f (\u043f\u043e\u043a\u0430 \u043d\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(help_text='\u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b', max_length=40, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u0438\u043c\u044f'),
        ),
    ]
