# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_auto_20170710_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrKitSelectorModelProxy',
            fields=[
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440 \u0438\u043b\u0438 \u041d\u0430\u0431\u043e\u0440',
                'proxy': True,
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440 \u2190\u2192 \u041d\u0430\u0431\u043e\u0440',
            },
            bases=('shop.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, help_text='\u0434\u043b\u044f \u0434\u043b\u0438\u043d\u043d\u043e\u0433\u043e \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f (\u043f\u043e\u043a\u0430 \u043d\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f)', max_length=1000, verbose_name='\u0414\u043b\u0438\u043d\u043d\u043e\u0435 \u0438\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='\u041d\u043e\u0432\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_product_kit',
            field=models.BooleanField(default=False, help_text="\u041d\u0415 \u041f\u0415\u0420\u0415\u041a\u041b\u042e\u0427\u0410\u0422\u042c \u0411\u0415\u0417 \u041d\u0415\u041e\u0411\u0425\u041e\u0414\u0418\u041c\u041e\u0421\u0422\u0418! \u041f\u0435\u0440\u0435\u043d\u043e\u0441\u0438\u0442 \u0442\u043e\u0432\u0430\u0440 \u0432 \u0442\u0430\u0431\u043b\u0438\u0446\u0443 '\u043d\u0430\u0431\u043e\u0440\u044b', \u044d\u0442\u043e \u0443\u0434\u0430\u043b\u0438\u0442 \u0437\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0443\u044e \u0446\u0435\u043d\u0443, \u0438 \u043e\u0441\u0442\u0430\u0442\u043a\u0438 \u0432 RetailCRM!", verbose_name='\u042f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u043d\u0430\u0431\u043e\u0440\u043e\u043c'),
        ),
    ]
