# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20170710_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='product_description_template',
            field=models.TextField(blank=True, help_text='\u041a\u043e\u043f\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043f\u0440\u0438 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u0438 \u043d\u043e\u0432\u043e\u0433\u043e \u0442\u043e\u0432\u0430\u0440\u0430 \u0447\u0435\u0440\u0435\u0437 CRM', verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_market_test',
            field=models.BooleanField(default=False, help_text='\u0422\u0435\u0441\u0442 \u0440\u044b\u043d\u043a\u0430, \u043b\u0438\u0431\u043e \u0442\u043e\u0432\u0430\u0440 \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043c\u044b \u0437\u0430\u043a\u0443\u043f\u0430\u0435\u043c \u043e\u043f\u0435\u0440\u0430\u0442\u0438\u0432\u043d\u043e. \u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435 \u0434\u043b\u044f \u0442\u0430\u043a\u043e\u0433\u043e \u0442\u043e\u0432\u0430\u0440\u0430 \u043d\u0435 \u0443\u0447\u0438\u0442\u044b\u0432\u0430\u0435\u0442\u0441\u044f!', verbose_name='\u0422\u0435\u0441\u0442 \u0440\u044b\u043d\u043a\u0430'),
        ),
    ]
