# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20170710_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 30, 18, 12, 24, 425196, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrambotrecipient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='telegrambotrecipient',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='telegrambotrecipient',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
