# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20170830_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('day_type', models.CharField(choices=[('normal', 'normal'), ('day-off', 'day-off')], max_length=10)),
            ],
        ),
    ]
