# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_operationalday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(help_text='\u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b', max_length=300, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
