# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_auto_20180213_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eng_name',
            field=models.CharField(blank=True, help_text='\u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b', max_length=300, verbose_name='\u0418\u043c\u044f (\u0430\u043d\u0433\u043b)'),
        ),
    ]
