# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_product_eng_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='eng_name',
        ),
        migrations.AddField(
            model_name='product',
            name='ru_name',
            field=models.CharField(blank=True, help_text='\u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b', max_length=300, verbose_name='\u0418\u043c\u044f (\u0440\u0443\u0441)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(help_text='\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0435 \u0438\u043c\u044f, \u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b', max_length=300, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
