# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_auto_20180804_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_info',
            field=models.CharField(max_length=100),
        ),
    ]
